CREATE DATABASE powerbi;
use powerbi;

select * from doctor_patients;
select * from hospital_er;


-- Q15. Identify the top 5 doctors who generated the most revenue but had the fewest patients. (SQL)
SELECT doctor_name, 
	SUM(total_bill) AS Total_Revenue,
    COUNT(DISTINCT patient_id) AS No_of_patients
FROM doctor_patients
GROUP BY doctor_name
ORDER BY Total_Revenue DESC, No_of_patients ASC
LIMIT 5;



-- Q16. Find the department where average waiting time decreased over three consecutive months. (SQL)
WITH MonthlyAverages AS (
    SELECT 
        department_referral,
        DATE_FORMAT(date, '%Y-%m-01') AS visit_month,
        AVG(patient_waittime) AS avg_wait
    FROM hospital_er
    GROUP BY department_referral, visit_month
),
TrendAnalysis AS (
    SELECT 
        department_referral,
        visit_month,
        avg_wait AS current_month_avg,
        LAG(avg_wait, 1) OVER (PARTITION BY department_referral ORDER BY visit_month) AS prev_month_avg,
        LAG(avg_wait, 2) OVER (PARTITION BY department_referral ORDER BY visit_month) AS two_months_ago_avg
    FROM MonthlyAverages
)
SELECT DISTINCT department_referral
FROM TrendAnalysis
WHERE current_month_avg < prev_month_avg 
  AND prev_month_avg < two_months_ago_avg
  AND prev_month_avg IS NOT NULL 
  AND two_months_ago_avg IS NOT NULL;
  
-- Q17. Determine the ratio of male to female patients for each doctor and rank the doctors based on this ratio. (SQL)
SELECT Doctor_Name, male_count, female_count, male_count / female_count AS male_female_ratio,
    RANK() OVER (ORDER BY male_count / female_count DESC) AS doctor_rank
FROM (SELECT d.Doctor_Name,
        SUM(CASE WHEN h.patient_gender = 'M' THEN 1 ELSE 0 END) AS male_count,
        SUM(CASE WHEN h.patient_gender = 'F' THEN 1 ELSE 0 END) AS female_count
    FROM doctor_patients d
    JOIN hospital_er h
        ON d.patient_id = h.patient_id
    GROUP BY d.Doctor_Name) t
WHERE female_count > 0;


-- Q18. Calculate the average satisfaction score of patients for each doctor based on their visits. (SQL)
SELECT 
    d.Doctor_Name, 
    COUNT(h.patient_id) AS total_patients_treated,
    ROUND(AVG(h.patient_sat_score), 2) AS avg_satisfaction_score
FROM doctor_patients d
JOIN hospital_er h
    ON d.patient_id = h.patient_id
GROUP BY d.Doctor_Name
ORDER BY avg_satisfaction_score DESC;

-- Q19. Find doctors who have treated patients from different races and calculate the diversity of their patient base. (SQL)
SELECT d.Doctor_Name, COUNT(DISTINCT h.patient_race) AS race_diversity_count
FROM doctor_patients d
JOIN hospital_er h
    ON d.patient_id = h.patient_id
WHERE h.patient_race IS NOT NULL
GROUP BY d.Doctor_Name
HAVING COUNT(DISTINCT h.patient_race) > 1;

-- Q20. Calculate the ratio of total bills generated by male patients to female patients for each department. (SQL)
WITH cte1 AS (SELECT d.department_referral,
        SUM(CASE WHEN h.patient_gender = 'M' THEN d.Total_Bill ELSE 0 END) AS male_total_bill,
        SUM(CASE WHEN h.patient_gender = 'F' THEN d.Total_Bill ELSE 0 END) AS female_total_bill
    FROM doctor_patients d
    JOIN hospital_er h
        ON d.patient_id = h.patient_id
    GROUP BY d.department_referral)
SELECT department_referral, male_total_bill, female_total_bill,
    ROUND(male_total_bill / female_total_bill, 2) AS male_female_bill_ratio
FROM cte1
WHERE female_total_bill > 0;

-- Q21. Update the patient satisfaction score for all patients who visited the "General Practice" department and had a waiting time of more than 30 minutes. 
-- Increase their satisfaction score by 2 points, but ensure that the satisfaction score does not exceed 10. (SQL)

ALTER Table hospital_er
add column updated_sat_score decimal(5,2);

UPDATE hospital_er
SET updated_sat_score = CASE 
                        WHEN patient_sat_score + 2 > 10 THEN 10
                        ELSE patient_sat_score + 2
                        END
WHERE department_referral = 'General Practice'
  AND patient_waittime > 30;

select department_referral,patient_waittime,
	coalesce(patient_sat_score,0) as old_sat_score,updated_sat_score
from hospital_er 
where department_referral="General Practice" and patient_waittime>30;



